In [2]:
#### Tensorflow Basics ####
import tensorflow as tf
print(tf.__version__)

2.3.1


In [3]:
# defining constants
A = tf.constant([[1, 2], [3, 4]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [5]:
# defining variables
a = tf.Variable([[2, 4], [6, 8]])
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 4],
       [6, 8]])>

In [6]:
# concatenate columns
Aa = tf.concat(values=[A, a], axis= 1)
Aa

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 2, 4],
       [3, 4, 6, 8]])>

In [9]:
# tensor of zeros/ones/random
zeros = tf.zeros(shape=(4, 4), dtype= tf.int32)
print(zeros)
ones = tf.ones(shape=(4, 4), dtype= tf.int32)
print(ones)
rand = tf.random.uniform(shape=(4, 4), dtype= tf.float32)
print(rand)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[0.8631772  0.7018106  0.33172274 0.5773442 ]
 [0.44827557 0.68042064 0.01575482 0.8821436 ]
 [0.34162366 0.07803762 0.52257836 0.6539862 ]
 [0.51420844 0.73064363 0.6464044  0.18486953]], shape=(4, 4), dtype=float32)


In [10]:
# casting to a different type
oldTensor = tf.constant([[1.2, 2.5, 3.6], [4.1, 5.3, 6.7]], dtype= tf.float32)
newTensor = tf.cast(oldTensor, tf.int32)
print(oldTensor)
print(newTensor)

tf.Tensor(
[[1.2 2.5 3.6]
 [4.1 5.3 6.7]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [11]:
# matrix multiplication
a = tf.constant([[7, 3], [4, 9]])
b = tf.constant([[5], [1]])

ab = tf.matmul(a, b)
print(ab)

tf.Tensor(
[[38]
 [29]], shape=(2, 1), dtype=int32)


In [ ]:
# more tensorflow functions in official documentation